branches:
  main:
    tag: ''
    increment: inherit
    source-branches:
      - master
    is-release-branch: true
  feature:
    increment: Minor
    tag: alpha
  release:
    increment: Minor
    tag: beta
    is-release-branch: false
  hotfix:
    increment: Patch
    tag: beta
ignore:
  sha: [ ]
BaseVersionSource:  83a2b22084a08430f2a457f42a5b42974e922868
