version: '3.8'
services:
  seq:
    container_name: apisolution_seq
    image: datalust/seq:latest
    ports:
      - 80:80
      - 5341:5341
    environment:
      ACCEPT_EULA: Y
    networks: 
      - apisolution
#if (mssql)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vendor-service-mssql
    ports:
      - 1433:1433
    env_file:
      - .env
#endif
#if (postgre)
  postgres:
    container_name: apisolution_postgre
    image: postgres
    env_file:
      - .env
    
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - apisolution
    restart: unless-stopped
#endif
networks:
  apisolution:
    driver: bridge
volumes:
  postgres: