version: '3.8'
services:
  seq:
    container_name: apisolution_seq
    image: datalust/seq:latest
    ports:
      - 80:80
      - 5341:5341
    environment:
      ACCEPT_EULA: Y
    networks: 
      - apisolution
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vendor-service-mssql
    ports:
      - 1433:1433
    env_file:
      - .env
networks:
  apisolution:
    driver: bridge
volumes:
  postgres: