
title: API Template Pack
email: support@threenine.co.uk
description: >-
  The API Template pack provides an opinionated implementation guide to making use of popular leading .net framework based tools and utilities to assist developers to quickly and efficiently develop secure, stable and resilient REST API’s.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.apitemplatepack.com" 
color_scheme: dark
logo: "/assets/images/site-logo.png"
twitter_username: threenine39
github_username:  threenine
remote_theme: just-the-docs/just-the-docs


plugins:
  - jekyll-feed
  - jekyll-seo-tag
    
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  
permalink: pretty 
aux_links:
  "API Template Pack on GitHub":
   - "//github.com/threenine/api-template"
aux_links_new_tab: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

footer_content: "&copy 2022 <a href=\"https://www.threenine.co.uk\">threenine.co.uk</a>"
ga_tracking: G-T1HJG6SP8H
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)   